from src.config import settings
from src.services.shisa import shisa_service
from twilio.rest import Client
from twilio.twiml.voice_response import Conference, Dial, Start, Stream, VoiceResponse


class TwilioService:
    def __init__(self):
        self.client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        self.from_number = settings.TWILIO_PHONE_NUMBER

    def incoming_call_response(self):
        resp = VoiceResponse()
        
        # Use Shisa AI (Japanese LLM) persona for greeting
        # In production, this could be dynamically generated by Shisa via API
        greeting = shisa_service.get_welcome_message()
        resp.say(greeting, voice='alice', language='ja-JP')
        
        # Play hold music loop or just pause
        # In a real app, you might use <Enqueue> but for simplicity we'll just keep the call alive
        resp.play(
            "https://archive.org/download/always-with-me-spirited-away-piano/Always%20With%20Me%20-%20Spirited%20Away%20%28Piano%29.mp3",
            loop=10,
        )
        return str(resp)

    def connect_to_conference(self, call_sid: str, conference_name: str):
        try:
            resp = VoiceResponse()

            # Start streaming audio to Deepgram via our WebSocket endpoint
            stream_url = settings.SERVER_URL.replace("http://", "wss://").replace("https://", "wss://")
            start = Start()
            start.stream(url=f"{stream_url}/api/ivr/stream")
            resp.append(start)

            dial = Dial()
            dial.conference(
                conference_name,
                start_conference_on_enter=True,
                end_conference_on_exit=True,
            )
            resp.append(dial)

            call = self.client.calls(call_sid).update(twiml=str(resp))
            print(f"Redirected {call_sid} to {conference_name}: {call.status}")
            return True
        except Exception as e:
            print(f"Error connecting to conference: {e}")
            return False


twilio_service = TwilioService()
